### PR TITLE
#4 maven/tycho 1.0.0 pomless build

### PR DESCRIPTION
**Pull request by paulvi**
2nd build with maven/tycho 1.0.0 pomless build.

Note that feature id was the same as plugin id, so it was changed.

This is not clean PR, because of whitespaces changes.
See https://github.com/nextinterfaces/http4e/compare/master...Nodeclipse:master?w=1 without 
whitespaces

I still cannot figure out why EGit does so.

### CODE REVIEW

**Comment by nextinterfaces** [comment]
Thanks @paulvi

**Comment by paulvi** [comment]
You need to check that ant build works, as I have to done so after changing feature id

For example https://github.com/nextinterfaces/http4e/blob/master/site.xml still references old feature id


Also changing feature id, will make trouble when users update, as they will have 2 plugins (I guess so)

**Comment by nextinterfaces** [comment]
Ant works. `feature id` is a manual version bump process, I can do it, just wondering why do we need to change it? And if so to what version? Thanks

**Comment by paulvi** [comment]
Tycho build is more strict, so it did not allow feature and plugin to have the same id `org.roussev.http4e.ui`  
More logical was to change feature, not plugin id. So now it is `org.roussev.http4e.feature`.  

Version is separate issue. There is maven one-liner command in README to bump version to new in all places (all plugins, feature, pom's), except site.

**Comment by nextinterfaces** [comment]
Probably we should drop `ant` build altogether and rely purely on maven? 

Also `org.roussev` is a dated name space, feel free if you have time, to rename `org.roussev.http4e` to --> `com.nextinterfaces.http4e.`

**Comment by paulvi** [comment]
> Probably we should drop ant build altogether and rely purely on maven?

in long run definitely yes, now it is a perl to see Ant build still working.

> Also org.roussev is a dated name space

usually base package name should be the same as id base.   
So that would be huge refactoring to change all to something new.

**Pull request merged**
